# ==============================================================================
# AUTOINICIO (EXEC-ONCE)
# ==============================================================================
exec-once=/home/d3rhund/.local/bin/orbit-wallpaper-engine
exec-once=pw-cat -p /home/d3rhund/.config/mango/assets/ps3.wav &
# --- Autostart del Stack Modular ---
# Barra de estado
exec-once=waybar

# Centro de notificaciones
exec-once=swaync

# Demonio de fondos de pantalla
exec-once=swww-daemon

# Agente de autenticación Polkit (necesario para apps gráficas con root)
exec-once=/run/current-system/sw/libexec/polkit-gnome-authentication-agent-1
exec-once=wl-paste --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store