# ==============================================================================
# ATAJOS DE TECLADO Y RATÓN (KEYBINDINGS)
# ==============================================================================

# Control del sistema y compositor
bind=SUPER,r,reload_config
bind=SUPER,m,quit
bind=SUPER,q,killclient, 

# Lanzadores de aplicaciones
bind=SUPER,Space,spawn, fuzzel
bind=SUPER,e,spawn,swaync-client -t -sw
bind=SUPER,Return,spawn,ghostty
bind=SUPER,b,spawn,zen
bind=SUPER,a,spawn,nemo

# Enfoque de ventanas (Vim)
bind=SUPER,Tab,focusstack,next
bind=SUPER,h,focusdir,left
bind=SUPER,l,focusdir,right
bind=SUPER,k,focusdir,up
bind=SUPER,j,focusdir,down

bind=ALT,h,focusdir,left
bind=ALT,l,focusdir,right
bind=ALT,k,focusdir,up
bind=ALT,j,focusdir,down

# Intercambiar ventanas (Swap)
bind=SUPER+SHIFT,k,exchange_client,up
bind=SUPER+SHIFT,j,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,l,exchange_client,right

# Mover y redimensionar flotantes
bind=CTRL+SHIFT,k,movewin,+0,-50
bind=CTRL+SHIFT,j,movewin,+0,+50
# Keymap hidden v1 begin 9af7582b 49c35a03
# Keymap hidden v1 data 62696e643d4354524c2b53484946542c682c6d6f766577696e2c2d35302c2b30
# Keymap hidden v1 end 9af7582b
# Keymap hidden v1 begin 5204ad55 08832a0d
# Keymap hidden v1 data 62696e643d4354524c2b53484946542c6c2c6d6f766577696e2c2b35302c2b30
# Keymap hidden v1 end 5204ad55

bind=CTRL+ALT,k,resizewin,+0,-50
bind=CTRL+ALT,j,resizewin,+0,+50
bind=CTRL+ALT,h,resizewin,-50,+0
bind=CTRL+ALT,l,resizewin,+50,+0

# Estados y modos de ventana
bind=ALT,backslash,togglefloating
bind=ALT,a,togglemaximizescreen
bind=ALT,f,togglefullscreen
bind=ALT+SHIFT,f,togglefakefullscreen
bind=SUPER,i,minimized
bind=SUPER+SHIFT,i,restore_minimized
bind=SUPER,g,toggleglobal
bind=SUPER,o,toggleoverlay
bind=ALT,Tab,toggleoverview
bind=ALT,z,toggle_scratchpad

# Márgenes (Gaps)
bind=ALT+SHIFT,x,incgaps,1
bind=ALT+SHIFT,z,incgaps,-1
bind=ALT+SHIFT,r,togglegaps

# Layouts
bind=SUPER,n,switch_layout
bind=ALT,t,setlayout,tile
bind=ALT,s,setlayout,scroller

# Scroller y Dwindle
bind=ALT,e,set_proportion,1.0
bind=SUPER,x,switch_proportion_preset
bind=ALT+SUPER+CTRL,h,scroller_stack,left
bind=ALT+SUPER+CTRL,l,scroller_stack,right
bind=ALT+SUPER+CTRL,k,scroller_stack,up
bind=ALT+SUPER+CTRL,j,scroller_stack,down
bind=ALT+SHIFT,Return,dwindle_toggle_split_direction

# Navegación entre escritorios (Tags)
bind=SUPER,Left,viewtoleft,0
bind=SUPER,Right,viewtoright,0
bind=CTRL,Left,viewtoleft_have_client,0
bind=CTRL,Right,viewtoright_have_client,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

# Cambiar a tag (Ctrl + 1..9)
bind=CTRL,1,view,1,0
bind=CTRL,2,view,2,0
bind=CTRL,3,view,3,0
bind=CTRL,4,view,4,0
bind=CTRL,5,view,5,0
bind=CTRL,6,view,6,0
bind=CTRL,7,view,7,0
bind=CTRL,8,view,8,0
bind=CTRL,9,view,9,0

# Mover a tag (Alt + 1..9)
bind=ALT,1,tag,1,0
bind=ALT,2,tag,2,0
bind=ALT,3,tag,3,0
bind=ALT,4,tag,4,0
bind=ALT,5,tag,5,0
bind=ALT,6,tag,6,0
bind=ALT,7,tag,7,0
bind=ALT,8,tag,8,0
bind=ALT,9,tag,9,0

# Monitores
bind=ALT+SHIFT,Left,focusmon,left
bind=ALT+SHIFT,Right,focusmon,right
bind=SUPER+ALT,Left,tagmon,left
bind=SUPER+ALT,Right,tagmon,right

# Ratón y Rueda
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=NONE,btn_middle,togglemaximizescreen,0

axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
