# ==============================================================================
# DISPOSITIVOS DE ENTRADA (TECLADO, RATÓN Y TOUCHPAD)
# ==============================================================================
# Teclado
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us

# Emulación de flechas con wtype
bind=SUPER+SHIFT,w,spawn,wtype -k Up
bind=SUPER+SHIFT,a,spawn,wtype -k Left
bind=SUPER+SHIFT,s,spawn,wtype -k Down
bind=SUPER+SHIFT,d,spawn,wtype -k Right

# Ratón
mouse_natural_scrolling=0
