# ==============================================================================
# CONFIGURACIÓN DE MANGO COMPOSITOR (MODULAR)
# ==============================================================================

source=~/.config/mango/conf.d/autostart.conf
source=~/.config/mango/conf.d/input.conf
source=~/.config/mango/conf.d/appearance.conf
source=~/.config/mango/conf.d/animations.conf
source=~/.config/mango/conf.d/layouts.conf
source=~/.config/mango/conf.d/misc.conf
source=~/.config/mango/conf.d/binds.conf
