# ==============================================================================
# AUTOINICIO (EXEC-ONCE)
# ==============================================================================
exec-once=/home/d3rhund/.local/bin/orbit-wallpaper-engine
exec-once=noctalia
